### PR TITLE
Make compatible with most(more) recent Django eg. 1.8.5

### PR DESCRIPTION
**Pull request by rwest**
**Not yet ready to merge.**

This PR is to get the website working on more recent versions of Django, eg. 1.8.4 or 1.8.5

### CODE REVIEW

**Comment by rwest** [comment]
Remaining problem seems to be that `getSolventList` in the `database.views` is needed by (or at least currently imported by) the `database.models`, which is imported by `database.forms` which is imported by `database.views`. The cyclic imports break things.

I think that the list of solvents should not be part of the views, if our forms and things depend on it. It is more fundamental. Should we have a separate `utils.py` or something?   Or else move it to models? (but it's not a model)

**Comment by nickvandewiele** [comment]
I tested the current state of RMG-website on this PR (a77c35d) with the current state of master of RMG-Py (https://github.com/ReactionMechanismGenerator/RMG-Py/commit/21b83e3a32ffb9009e1b64b11b2a777f61394345) on my local dev server by
- clicking on buttons
- computing thermo

and I could successfully visit the website without problems except:
- the Cactus functionality (probably my website run within a VM could not access Cactus)
- molecule depictions

**Comment by nickvandewiele** [comment]
My understanding is that the following error is caused by parsing URLs that contain an adjacency list. In the adj list the HTML compatible characters, e.g. `%20`, should be replaced by their _normal_ equivalents, e.g. a whitespace, so that the adjlist conversion code in `rmgpy.molecule.adjlist` can successfully split the adj list string based on delimiters.

I should read some more on these special character conversions and differences before I change something here. The URLs of the production website seem to have similar characters but the parsing works there.

```
Environment:


Request Method: GET
Request URL: http://localhost:4567/database/kinetics/reaction/reactant1%3D1%2520C%2520u0%2520p0%2520c0%2520%7B2,S%7D%2520%7B3,S%7D%2520%7B4,S%7D%2520%7B5,S%7D%3B2%2520H%2520u0%2520p0%2520c0%2520%7B1,S%7D%3B3%2520H%2520u0%2520p0%2520c0%2520%7B1,S%7D%3B4%2520H%2520u0%2520p0%2520c0%2520%7B1,S%7D%3B5%2520H%2520u0%2520p0%2520c0%2520%7B1,S%7D%3B__reactant2%3Dmultiplicity%25202%3B1%2520H%2520u1%2520p0%2520c0%3B__product1%3Dmultiplicity%25202%3B1%2520C%2520u1%2520p0%2520c0%2520%7B2,S%7D%2520%7B3,S%7D%2520%7B4,S%7D%3B2%2520H%2520u0%2520p0%2520c0%2520%7B1,S%7D%3B3%2520H%2520u0%2520p0%2520c0%2520%7B1,S%7D%3B4%2520H%2520u0%2520p0%2520c0%2520%7B1,S%7D%3B__product2%3D1%2520H%2520u0%2520p0%2520c0%2520%7B2,S%7D%3B2%2520H%2520u0%2520p0%2520c0%2520%7B1,S%7D%3B

Django Version: 1.8.5
Python Version: 2.7.10
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'rmgweb.main',
 'rmgweb.main.templatetags',
 'rmgweb.database',
 'rmgweb.pdep',
 'rmgweb.rmg')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')


Traceback:
File "/home/vagrant/anaconda/envs/rmg/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/vagrant_data/Code/RMG-website/rmgweb/database/views.py" in kineticsData
  2166.     reactantList.append(moleculeFromURL(reactant1))
File "/vagrant_data/Code/RMG-website/rmgweb/main/tools.py" in moleculeFromURL
  71.     molecule = Molecule().fromAdjacencyList(str(adjlist.replace(';', '\n')))
File "/vagrant_data/Code/RMG-Py/rmgpy/molecule/adjlist.py" in fromAdjacencyList
  519.         aid = int(data[0].strip('.'))

Exception Type: ValueError at /database/kinetics/reaction/reactant1=1%20C%20u0%20p0%20c0%20{2,S}%20{3,S}%20{4,S}%20{5,S};2%20H%20u0%20p0%20c0%20{1,S};3%20H%20u0%20p0%20c0%20{1,S};4%20H%20u0%20p0%20c0%20{1,S};5%20H%20u0%20p0%20c0%20{1,S};__reactant2=multiplicity%202;1%20H%20u1%20p0%20c0;__product1=multiplicity%202;1%20C%20u1%20p0%20c0%20{2,S}%20{3,S}%20{4,S};2%20H%20u0%20p0%20c0%20{1,S};3%20H%20u0%20p0%20c0%20{1,S};4%20H%20u0%20p0%20c0%20{1,S};__product2=1%20H%20u0%20p0%20c0%20{2,S};2%20H%20u0%20p0%20c0%20{1,S};
Exception Value: invalid literal for int() with base 10: '2%20H%20u0%20p0%20c0%20{1,S}'

```

**Comment by rwest** [comment]
I'm guessing the error you report is related to the last commit, b15fd518a3d42addbe91379ebd07506c108bedfa "do not replace white space chars in adj lists". Was that necessary for some other reason?

**Comment by nickvandewiele** [comment]
Django 1.8.5 is alive on dev.rmg.mit.edu along with a small patch for RMG-Py: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/481

Please test it and see if you find stuff that does not work!

**Pull request merged**
