### PR TITLE
Django 185

### PR DESCRIPTION
**Pull request by nick-rc**
Do not merge, still not working fully.
I’m not sure if this problem is on my end or if there is a problem with the code itself.

Had to include all methods located in rmgweb.database.tools to remove
the error found in the last commit. New error has been generated: from
rmgpy import settings
ImportError: No module named rmgpy

### CODE REVIEW

**Comment by nick-rc** [comment]
I believe that I've already run RMG-py within this repository and downloaded necessary add-ons, but this may be an issue unrelated to the code.

**Comment by nickvandewiele** [comment]
Hi @nick-rc : thanks for helping to fix this issue!

Don't forget to combine these _work-in-progress_ commits when you have figured out the remaining bugs. See [here] (http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html). Eventually one of the owners of this repository can then add that/those commit(s) to the pull request that already exists (https://github.com/ReactionMechanismGenerator/RMG-website/pull/96).

**Comment by rwest** [comment]
The `ImportError: No module named rmgpy` problem can probably be solved by adding the RMG-Python folder to your `$PYTHONPATH` environment variable.

**Comment by connie** [comment]
What's the difference between this pull request and https://github.com/ReactionMechanismGenerator/RMG-website/pull/96?

**Comment by nickvandewiele** [comment]
I would only continue with #96 , which is not ready to merge yet.

**Comment by rwest** [comment]
I think the main difference was that @nick-rc is able to push to this one but not #96.
I've now invited him to the relevant group so he has permission to push to #96.

**Comment by nick-rc** [comment]
Closing this pull request, #96 is more up-to-date

**Pull request closed without merging**
